### ISSUE TITLE
JOSS Review

### ISSUE THREAD

**Issue by mwegrzyn** [harvard-nrg/dwiqc#21]
Dear @danielasay,

my name is Martin and I am one of the reviewers assigned to your submission to JOSS. Thank you for your work on dwiqc. One of the things I have to check regards automated testing: _Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?_
Could you point me to the relevant places in your repository or add automated tests if they are not implemented yet? Thank you!

Best,
Martin

**Comment by danielasay** [comment]
Hi Martin,

Thank you for taking the time to review our work! We have one automated test at the moment which checks all of the python scripts in the repository for syntax errors with pylint. You can find it under the Actions tab in the repository. This test gets kicked off every time a commit is pushed to the main branch of dwiqc.

Are there additional tests you would suggest adding?

Look forward to hearing from you!

Daniel

**Comment by mwegrzyn** [comment]
Dear @danielasay,

thank you. That looks good!

Best,
Martin
